<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<AssemblyName>Au.Net4</AssemblyName>
		<OutDir>$(SolutionDir)_</OutDir>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AutoGenerateBindingRedirects>False</AutoGenerateBindingRedirects>
		<ImplicitUsings>disable</ImplicitUsings>
		<Configurations>Release</Configurations>
		<NuGetAudit>False</NuGetAudit>
		<PreferNativeArm64>True</PreferNativeArm64>
		<IsPublishable>False</IsPublishable>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PolySharp" Version="1.16.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>