#if !EMPTY

static class folders {
	#region generated by macro "Auto create special folders class from KNOWNFOLDERID"
	
	public static FolderPath CommonPrograms => _Get(0x0139D44E, 0x6AFE49F2, 0x86903DAF, 0xCAE6FFB8);
	public static FolderPath Downloads => _Get(0x374DE290, 0x123F4565, 0x916439C4, 0x925E467B);
	public static FolderPath ProgramData => _Get(0x62AB5D82, 0xFDC14DC3, 0xA9DD070D, 0x1D495D97);
	public static FolderPath ProgramFiles => _Get(0x905e63b6, 0xc1bf494e, 0xb29c65b7, 0x32d3d21a);
	//public static FolderPath ProgramFiles => new(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles));
	
	#endregion
	
	#region other paths
	
	//public static FolderPath Temp => new(Path.GetTempPath().TrimEnd('\\')); //Microsoft FP
	
	public static FolderPath ThisApp => new(ThisAppBS.TrimEnd('\\'));
	
	public static string ThisAppBS => AppContext.BaseDirectory;
	
	#endregion
	
	#region private functions
	
	static FolderPath _Get(uint a, uint b, uint c, uint d) {
		var guid = new _Api.KNOWNFOLDERID(a, b, c, d);
		if (0 != _Api.SHGetKnownFolderPath(guid, _Api.KNOWN_FOLDER_FLAG.KF_FLAG_DONT_VERIFY, default, out string R)) R = null;
		return new(R);
	}
	
	#endregion
	
	#region API
	
	static class _Api {
		//GUID that can be inited with 4 uints.
		internal struct KNOWNFOLDERID {
			uint _a; ushort _b, _c; byte _d, _e, _f, _g, _h, _i, _j, _k;
			
			public KNOWNFOLDERID(uint a, uint b, uint c, uint d) {
				_a = a;
				_b = (ushort)(b >> 16);
				_c = (ushort)b;
				_d = (byte)(c >> 24);
				_e = (byte)(c >> 16);
				_f = (byte)(c >> 8);
				_g = (byte)c;
				_h = (byte)(d >> 24);
				_i = (byte)(d >> 16);
				_j = (byte)(d >> 8);
				_k = (byte)d;
			}
		}
		
		[DllImport("shell32.dll")]
		internal static extern int SHGetKnownFolderPath(in KNOWNFOLDERID rfid, KNOWN_FOLDER_FLAG dwFlags, IntPtr hToken, out string ppszPath);
		
		[Flags]
		internal enum KNOWN_FOLDER_FLAG : uint {
			KF_FLAG_SIMPLE_IDLIST = 0x00000100,
			KF_FLAG_NOT_PARENT_RELATIVE = 0x00000200,
			KF_FLAG_DEFAULT_PATH = 0x00000400,
			KF_FLAG_INIT = 0x00000800,
			KF_FLAG_NO_ALIAS = 0x00001000,
			KF_FLAG_DONT_UNEXPAND = 0x00002000,
			KF_FLAG_DONT_VERIFY = 0x00004000,
			KF_FLAG_CREATE = 0x00008000,
			KF_FLAG_NO_APPCONTAINER_REDIRECTION = 0x00010000,
			KF_FLAG_ALIAS_ONLY = 0x80000000
		}
	}
	
	#endregion
	
}

struct FolderPath {
	readonly string _path;
	
	public FolderPath(string path) { _path = path; }
	
	public static explicit operator FolderPath(string path) => new(path);
	public static implicit operator string(FolderPath f) => f._path;
	
	public override string ToString() => _path;
	
	public string Path => _path;
	
	public static string operator +(FolderPath fp, string append) {
		if (fp._path.NE()) throw new ArgumentException("No folder path.");
		if (append[0] is '\\' or '/') return fp._path + append;
		return System.IO.Path.Combine(fp._path, append);
	}
}
#endif
