name: publish LA

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: |
          $msbuild = "C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild Au.sln -t:build -p:Configuration=Release -p:Platform="Any CPU" -verbosity:minimal
          & $msbuild Au.sln -t:build -p:Configuration=Release -p:Platform=ARM64 -verbosity:minimal
          & $msbuild Au.sln -t:build -p:Configuration=Release -p:Platform=x86 -verbosity:minimal

      - name: Install Master Packager Dev
        run: |
          winget install --id=MasterPackager.MasterPackagerDev -e --accept-source-agreements --accept-package-agreements --skip-dependencies

      - name: Create installer
        run: |
          Other\BuildEvents\bin\Debug\BuildEvents.exe createInstaller
  
      - name: upload unsigned artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v7
        with:
          path: _\LibreAutomate.msi
          archive: false
          overwrite: true
    
      - name: submit signing request
        uses: signpath/github-action-submit-signing-request@v3
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '07d655b1-2c96-4986-a3f0-5f43d7e86ec1'
          project-slug: 'LibreAutomate'
          signing-policy-slug: 'test-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: '_\signed'
          wait-for-completion-timeout-in-seconds: 3600
          skip-decompress: true
  
      - name: upload signed artifact
        uses: actions/upload-artifact@v7
        with:
          path: _\signed\LibreAutomate.msi
          archive: false
          overwrite: true
